import os
import requests
import yfinance as yf
from google import genai
from google.genai import types
from datetime import datetime
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# --- 1. CONFIGURATION ---
NEWS_API_KEY = os.getenv("NEWS_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
SENDER_EMAIL = os.getenv("EMAIL_USER")
SENDER_PASSWORD = os.getenv("EMAIL_PASS")
RECEIVER_EMAIL = "your_email@example.com"

# Initialize New Unified Client
client = genai.Client(api_key=GEMINI_API_KEY)

# --- 2. LIVE MARKET & COMMODITY ENGINE ---
def get_live_market_data():
    """Fetches real-time prices for Stocks, Currency, Gold, and Silver."""
    tickers = {
        "NIFTY 50": "^NSEI",
        "SENSEX": "^BSESN",
        "USD/INR": "INR=X",
        "GOLD (MCX)": "GC=F",   # Global Spot Gold
        "SILVER (MCX)": "SI=F"  # Global Spot Silver
    }
    
    data = {}
    print("Gathering live market data...")
    for label, symbol in tickers.items():
        try:
            ticker = yf.Ticker(symbol)
            hist = ticker.history(period='1d')
            if not hist.empty:
                price = hist['Close'].iloc[-1]
                # Simple formatting: Currency vs Points
                if "INR" in label:
                    data[label] = f"₹{price:.2f}"
                elif "GOLD" in label or "SILVER" in label:
                    data[label] = f"${price:,.2f}" # Per Oz
                else:
                    data[label] = f"{price:,.2f}"
            else:
                data[label] = "N/A"
        except:
            data[label] = "Error"
    
    return data

# --- 3. NEWS GATHERING ---
def get_premium_news():
    """Fetches high-impact news stories."""
    url = f"https://newsapi.org/v2/top-headlines?country=in&category=business&apiKey={NEWS_API_KEY}"
    try:
        response = requests.get(url).json()
        return response.get('articles', [])[:5] # Top 5 stories
    except Exception as e:
        print(f"News Error: {e}")
        return []

# --- 4. AI ANALYST (WITH BLOCK_NONE) ---
def analyze_article(article):
    """Analyzes news with zero safety filtering (BLOCK_NONE)."""
    
    # Configure safety to allow all content types
    config = types.GenerateContentConfig(
        safety_settings=[
            types.SafetySetting(category="HARM_CATEGORY_HARASSMENT", threshold="BLOCK_NONE"),
            types.SafetySetting(category="HARM_CATEGORY_HATE_SPEECH", threshold="BLOCK_NONE"),
            types.SafetySetting(category="HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold="BLOCK_NONE"),
            types.SafetySetting(category="HARM_CATEGORY_DANGEROUS_CONTENT", threshold="BLOCK_NONE"),
        ],
        system_instruction="Analyze this news for an Indian investor. Be blunt, objective, and strategic."
    )

    prompt = f"""
    CONTEXT: {article.get('description', 'No description available')}
    TITLE: {article.get('title')}
    
    Output HTML format only.
    Use <p> and <strong> tags.
    Identify: 1. Core Impact, 2. Sentiment (Bullish/Bearish/Neutral).
    """

    try:
        response = client.models.generate_content(
            model="gemini-1.5-flash",
            contents=prompt,
            config=config
        )
        return response.text.replace("```html", "").replace("```", "").strip()
    except Exception as e:
        return f"<p>Analysis skipped: {str(e)[:50]}</p>"

# --- 5. NEWSLETTER COMPOSER ---
def compose_email(market_data, analysis_html):
    date_str = datetime.now().strftime("%B %d, %Y")
    
    # Market Table HTML
    market_rows = "".join([f"<tr><td style='padding:8px; border-bottom:1px solid #eee;'>{k}</td><td style='padding:8px; border-bottom:1px solid #eee; font-weight:bold;'>{v}</td></tr>" for k,v in market_data.items()])
    
    return f"""
    <html>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; background: #f4f4f4; padding: 20px;">
        <div style="max-width: 600px; margin: auto; background: #fff; padding: 30px; border-top: 8px solid #b71c1c;">
            <h1 style="margin:0; font-size: 24px;">Daily Intel Report</h1>
            <p style="color: #666;">{date_str}</p>
            
            <div style="background: #fdf2f2; padding: 15px; border-radius: 5px; margin: 20px 0;">
                <h3 style="margin-top:0; color:#b71c1c;">📊 Market & Commodities</h3>
                <table width="100%" style="font-size: 14px; border-collapse: collapse;">
                    {market_rows}
                </table>
            </div>
            
            <div style="margin-top: 30px;">
                {analysis_html}
            </div>
            
            <div style="font-size: 10px; color: #aaa; text-align: center; margin-top: 40px;">
                Generated by AI Intelligence Bot v3.0 | 2026 Edition
            </div>
        </div>
    </body>
    </html>
    """

# --- 6. DISPATCH ---
def run_report():
    print("Starting Intelligence Bot...")
    
    # Get Data
    market_data = get_live_market_data()
    articles = get_premium_news()
    
    # Process Analysis
    full_analysis = ""
    for art in articles:
        print(f"Analyzing: {art['title'][:40]}...")
        full_analysis += f"<h3>{art['title']}</h3>"
        full_analysis += analyze_article(art)
        full_analysis += "<hr style='border:0; border-top:1px solid #eee;'>"

    # Send Email
    email_body = compose_email(market_data, full_analysis)
    
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = f"Intel Report: {datetime.now().strftime('%d %b %Y')}"
    msg.attach(MIMEText(email_body, 'html'))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.send_message(msg)
        print("✅ Report dispatched successfully!")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

if __name__ == "__main__":
    run_report()
