import os
import requests
import google.generativeai as genai
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

# --- 1. SECURE CONFIGURATION ---
NEWS_API_KEY = os.getenv("NEWS_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
SENDER_EMAIL = os.getenv("EMAIL_USER")
SENDER_PASSWORD = os.getenv("EMAIL_PASS")

# Initialize Gemini 1.5 Flash
genai.configure(api_key=GEMINI_API_KEY)
ai_model = genai.GenerativeModel('gemini-1.5-flash')

# --- 2. HIGH-QUALITY NEWS ENGINE ---
def get_premium_news():
    """Fetches high-quality news from trusted financial and geopolitical sources."""
    trusted_sources = "reuters.com,bloomberg.com,wsj.com,ft.com,economist.com,cnbc.com"
    queries = ['central banking', 'geopolitics', 'global markets', 'national economy']
    
    curated_articles = []
    for q in queries:
        url = (f"https://newsapi.org/v2/everything?q={q}&domains={trusted_sources}"
               f"&language=en&sortBy=relevancy&pageSize=2&apiKey={NEWS_API_KEY}")
        try:
            response = requests.get(url).json()
            articles = response.get('articles', [])
            for art in articles:
                art['custom_category'] = q.upper()
                curated_articles.append(art)
        except Exception as e:
            print(f"Error fetching {q}: {e}")
            
    return curated_articles

# --- 3. PROFESSIONAL AI ANALYST ---
def perform_deep_analysis(article):
    """Uses AI to generate impact analysis, pros, and cons."""
    prompt = f"""
    Act as a Lead Financial Analyst. Analyze this report:
    Title: {article['title']}
    Source: {article['source']['name']}
    Description: {article['description']}

    Format the output in HTML:
    <strong>EXECUTIVE SUMMARY:</strong> [1 sentence summary] <br>
    <strong>MARKET IMPACT:</strong> [How this affects banking/finance] <br>
    <strong>GEOPOLITICAL SHIFT:</strong> [How this affects international news] <br>
    
    <table border="1" style="width:100%; border-collapse: collapse; margin-top:10px; font-size: 13px;">
        <tr style="background-color: #f8f9fa;">
            <th style="padding: 5px; color: #2ecc71;">PROS / OPPORTUNITIES</th>
            <th style="padding: 5px; color: #e74c3c;">CONS / RISKS</th>
        </tr>
        <tr>
            <td style="padding: 8px;">[Bullet point of positive outcome]</td>
            <td style="padding: 8px;">[Bullet point of potential risk]</td>
        </tr>
    </table>
    """
    try:
        response = ai_model.generate_content(prompt)
        return response.text
    except Exception:
        return "Analysis currently unavailable for this story."

# --- 4. NEWSLETTER DESIGN (HTML) ---
def build_newsletter(content_html):
    date_str = datetime.now().strftime("%B %d, %2025")
    return f"""
    <html>
    <body style="font-family: 'Times New Roman', Times, serif; color: #1a1a1a; background-color: #f4f4f4; padding: 20px;">
        <div style="max-width: 650px; margin: auto; background: white; padding: 40px; border: 1px solid #ccc;">
            <div style="text-align: center; border-bottom: 4px double #000; padding-bottom: 10px; margin-bottom: 20px;">
                <h1 style="margin: 0; font-size: 32px; letter-spacing: 1px;">THE GLOBAL INTELLIGENCE</h1>
                <p style="margin: 5px 0; color: #666; text-transform: uppercase;">Finance • Geopolitics • Banking</p>
                <p style="font-size: 14px;">{date_str}</p>
            </div>
            {content_html}
            <div style="text-align: center; font-size: 11px; color: #aaa; margin-top: 40px; border-top: 1px solid #eee; padding-top: 10px;">
                Generated by AI Intelligence System | Proprietary Content
            </div>
        </div>
    </body>
    </html>
    """

# --- 5. DISPATCH SYSTEM ---
def dispatch_email(html_report):
    if not os.path.exists("recipients.txt"):
        print("recipients.txt missing.")
        return

    with open("recipients.txt", "r") as f:
        emails = [line.strip() for line in f.readlines() if line.strip()]

    for target in emails:
        msg = MIMEMultipart()
        msg['From'] = SENDER_EMAIL
        msg['To'] = target
        msg['Subject'] = f"📊 Intel Brief: {datetime.now().strftime('%d %b')}"
        msg.attach(MIMEText(html_report, 'html'))
        
        try:
            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
                server.login(SENDER_EMAIL, SENDER_PASSWORD)
                server.send_message(msg)
            print(f"✅ Dispatched to {target}")
        except Exception as e:
            print(f"❌ Dispatch failed for {target}: {e}")

if __name__ == "__main__":
    print("🚀 Starting Intelligence Gathering...")
    news_items = get_premium_news()
    
    body_parts = []
    for item in news_items:
        analysis = perform_deep_analysis(item)
        section = f"""
        <div style="margin-bottom: 35px;">
            <small style="color: #e67e22; font-weight: bold;">{item['custom_category']}</small>
            <h2 style="margin: 5px 0 10px 0; color: #000; font-size: 22px;">{item['title']}</h2>
            <div style="font-size: 15px; color: #333;">
                {analysis}
            </div>
            <p style="font-size: 13px;"><a href="{item['url']}" style="color: #0056b3;">Source: {item['source']['name']} →</a></p>
        </div>
        """
        body_parts.append(section)
    
    final_report = build_newsletter("".join(body_parts))
    dispatch_email(final_report)
